### ISSUE TITLE
Arduino Shield not being detected by the router with the ArtGateOne program

### ISSUE THREAD

**Issue by nt2ds** [ArtGateOne/ArtGateOne-DMX#3]
Hello, i recently bought the arduino shield 2 (W5500) I've made sure its a genuine one. The first time I ran the project it worked normally, got detected by the program I'm using (Avolites TitanGo) and could easily send DMX data.
I unplugged it and plugged it some hours later and then nothing. It was not even detected on the router's attached devices.
I saw that the ethernet shield was getting pretty hot and i thought something might had happened to the ethernet shield and I sent it back. After some days they tell me that the ethernet shield is working fine but they will change it. They send the new shield which I received today. I uploaded the program to the arduino and again nothing. Neither being detected neither typing the IP.
I had another idea. I saw the examples tab and saw that there is a DhcpPrintAddress example for the ethernet shield which prints the ip given by the DHCP. This program worked fine (it printed the IP 192.168.1.123) but I couldn't still see it on the attached devices from the router configuration. There goes another idea, I will ping the shield, after I pinged the shield the device showed in the attached devices on the router (keep in mind that I still have the DhcpPrintAddress example program). I uploaded the ArtGateOne_1.3_NO_OLED the program was uploaded successfully but still nothing. I tried pinging with the same I.P (and +- some numbers on the host octave). Pinging the same I.P. got me a result saying "request timed out" but the device was still not detected by the router. How can I fix that?

P.S. all libraries are up to date and the LED's on the RJ45 port light up normally

Thanks in advance
Nick

**Comment by ArtGateOne** [comment]
It's best if you had an OLED - because it would be known what IP is stored in the Arduino's memory.
These settings are saved in the eprom - and they are saved there at the first start ...

You can clear the eprom (the program is in the examples)
Or read the eprom - IPAddress ip
(EEPROM.read(513), EEPROM.read(514), EEPROM.read(515), EEPROM.read(516)

if you have not changed the settings to DHCP or another IP address

This arduino has address 2.0.0.10


So connect the arduino to the computer - set the static address of the cards in the computer - e.g. 2.0.0.2 with the mask 255.0.0.0 and see if it is detected - e.g. with the artnetominator program.

**Comment by nt2ds** [comment]
Did everything you said. Cleared the eeprom and now the web interface loads normally! I disabled the DHCP and set it to static IP Address (2.0.0.10) and plugged it to the computer ethernet port and set the IP Address of the network adapter to 2.0.0.2 and subnet mask 255.0.0.0.
I opened ArtNetominator and the node gets detected normally but I cant choose it on programs like QLC+. I can only choose the network adapter (2.0.0.2) and in the artnominator program the output isn't going to the ArtGateOne node but instead on the network adapter.
The other 2 network adapters (except for 127.0.0.1) is a loodback adapter which I created long ago for sth else and the 192.168.1.120 is the wireless adapter
![Screenshot_1](https://user-images.githubusercontent.com/89281795/205283168-c22a6b38-7e42-48c8-afb8-5bd9454eb57c.png)
![Screenshot_2](https://user-images.githubusercontent.com/89281795/205283174-2b539dc5-4742-44cc-91b7-80e815b4f455.png)
![Screenshot_3](https://user-images.githubusercontent.com/89281795/205283175-a1cf666a-7e40-4e12-8f20-8401342258e8.png)

**Comment by nt2ds** [comment]
Ok, i managed to solve the problem. I set the IP of the network adapter the same as the arduino and it works fine!
Also, what is the refresh rate of this? 40Hz? or lower?

**Comment by ArtGateOne** [comment]
Unfortunately, I do not have a dmx tester to check it.

**Comment by Kawaiito** [comment]
so i make a oled version an it works for me fine i have only issue with the wiznet networkcard. but i see you have aonther problem.

**Comment by ArtGateOne** [comment]
Most of the problems reported here - rather result from the user - i.e. incorrect IP address setting.

I also experienced problems with the network shield and cooperation with the router - but this is the fault of the electronics, not the software.

**Comment by Kawaiito** [comment]
my problem was the wiznet shield so when my ardruinio get power the shield dont starts so i must press reset so it starts. so i solder a capasitor and it works fine so any have issues in the future with the same who can ask me

**Comment by ArtGateOne** [comment]
> Did everything you said. Cleared the eeprom and now the web interface loads normally! I disabled the DHCP and set it to static IP Address (2.0.0.10) and plugged it to the computer ethernet port and set the IP Address of the network adapter to 2.0.0.2 and subnet mask 255.0.0.0. I opened ArtNetominator and the node gets detected normally but I cant choose it on programs like QLC+. I can only choose the network adapter (2.0.0.2) and in the artnominator program the output isn't going to the ArtGateOne node but instead on the network adapter. The other 2 network adapters (except for 127.0.0.1) is a loodback adapter which I created long ago for sth else and the 192.168.1.120 is the wireless adapter ![Screenshot_1](https://user-images.githubusercontent.com/89281795/205283168-c22a6b38-7e42-48c8-afb8-5bd9454eb57c.png) ![Screenshot_2](https://user-images.githubusercontent.com/89281795/205283174-2b539dc5-4742-44cc-91b7-80e815b4f455.png) ![Screenshot_3](https://user-images.githubusercontent.com/89281795/205283175-a1cf666a-7e40-4e12-8f20-8401342258e8.png)

You did everything correctly - Artnetominator won't show any Artnet data for the node because it doesn't send any data to ArtNet, it only receives and sends it as DMX - so everything looks fine.
