### ISSUE TITLE
UART1 cannot get to work

### ISSUE THREAD

**Issue by Alfiszcze** [ArtGateOne/ArtGateOne-DMX#5]
If I comment no needed uart0 in dmx.h program won't compile. If I define to use uart1 in program it is compiling correctly but use still uart0. Can someone check if this possible?

**Comment by ArtGateOne** [comment]
Hello - this code was prepared only for Arduino Uno, which has only uart0.

I used an old DMX library by Toni Merino - with a small modification to make it compilable on a newer version of Arduino IDE.

You can take a look at the code for Arduino Mega - prepared for 4 universes. However, this hardware is too weak, so it won't work correctly.

Try experimenting with the previous version of the code and the library (it's a bit different!).

Limit it, for example, to two universes, and it should work relatively correctly.

There is a chance that there will be 3 OUT and 1 IN - but I haven't tested it!

https://github.com/ArtGateOne/ArtGateOne_DMX_4U

**Comment by ArtGateOne** [comment]
U use ArduinoDmx0 ?

Try 1 for uart1 :P

ArduinoDmx1.set_control_pin(-1);  // Arduino output pin for MAX485 input/output control (connect to MAX485-1 pins 2-3)(-1 not used)
  ArduinoDmx1.set_tx_address(1);    // set rx1 start address
  ArduinoDmx1.set_tx_channels(512); // 2 to 2048!! channels in DMX1000K (512 in standard mode) See lib_dmx.h  *** new *** EXPERIMENTAL
  ArduinoDmx1.init_tx(DMX512);      // starts universe 1 as tx, standard DMX 512

**Comment by ArtGateOne** [comment]
Was this information helpful?

**Comment by ArtGateOne** [comment]
Hej Alf ! Udało CI się odpalić ten uart1 ?

**Comment by ArtGateOne** [comment]
This project is intended for the Arduino Uno, which has only one UART0.

**Comment by Alfiszcze** [comment]
It worked. Thanx a lot.
