### ISSUE TITLE
The scanner in Jinx! does not work.

### ISSUE THREAD

**Issue by MichurinD** [ArtGateOne/ArtGateOne-DMX#6]
The scanner in Jinx! does not work.
If the inputs are not used, then they must be marked as 0x08, then everything will work.

  ArtPoolReply[178] = 0x08; // GoodInput 0
  ArtPoolReply[179] = 0x08; // GoodInput 1
  ArtPoolReply[180] = 0x08; // GoodInput 2
  ArtPoolReply[181] = 0x08; // GoodInput 3

**Comment by MichurinD** [comment]
GoodInput [4] Int8 This array defines input status of the node.

7 Set – Data received.
6 Set – Channel includes DMX512 test packets.
5 Set – Channel includes DMX512 SIP’s.
4 Set – Channel includes DMX512 text packets.
3 Set – Input is disabled.
2 Set – Receive errors detected.
1-0     Unused and transmitted as zero.

3 bit Set – Input is disabled.

0x08

**Comment by ArtGateOne** [comment]
"Thank you very much for this information...

Other programs such as DMX Workshop, The Artnetominator, as well as lighting control software correctly recognize ArtPoolReply."

**Comment by ArtGateOne** [comment]
Setting 0x08 only for the first "GoodInput" is sufficient for Jinx to correctly recognize the response from the device - I'm making the correction to the code.

Thank you once again!
